apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tasks
spec:
  steps:
    - name: cleanup-resources
      image: alpine:latest
      script:
        - echo "Cleaning up resources..."
    - name: run-unit-tests
      image: python:3.9
      script:
        - pip install -r requirements.txt  # Install project dependencies
        - nosetests  # Run unit tests with nose