apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  params:
    - name: directory
      type: string
      description: The directory to clean up
      default: "/tmp"
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:3.14
      command:
        - sh
        - -c
      args:
        - |
          rm -rf $(params.directory)/*
      volumeMounts:
        - name: workspace
          mountPath: $(params.directory)