apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-and-test-task
spec:
  params:
    - name: directory
      type: string
      description: The directory to clean up
      default: "/tmp"
    - name: test_directory
      type: string
      description: The directory containing test files
      default: "/tests"
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:3.14
      command:
        - sh
        - -c
      args:
        - |
          rm -rf $(params.directory)/*
      volumeMounts:
        - name: source
          mountPath: $(params.directory)

    - name: run-tests
      image: python:3.9
      command:
        - sh
        - -c
      args:
        - |
          pip install -r $(workspaces.source.path)/requirements.txt
          nosetests $(params.test_directory)
      volumeMounts:
        - name: source
          mountPath: /source