name: CI Workfkow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint_test_deploy:
        runs-on: ubuntu-latest
        name: Lint, Checkout and Unit Tests

        steps:
          - name: Checkout code 
            uses: actions/checkout@v2 

          - name: Install dependencies 
            run: pip install -r requirements.txt 
          
          - name: Lint with Flake8
            run: flake8 .
          - name: Run unit tests
            run: nosetests


